spring:
  mvc:
    problemdetails:
      enabled: true
  application:
    name: notification-service
  profiles:
    default: local
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    url: jdbc:h2:mem:notifications;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

server:
  port: 8084
